name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: pytest

  deploy:
    if: success()
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with: 
        lfs: true
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Deploy to VPS
      env:
        PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
      run: |
        echo "$PRIVATE_KEY" > deploy_key
        chmod 600 deploy_key
        scp -i deploy_key -o StrictHostKeyChecking=no /home/runner/work/my-project/my-project/flask-app/main.py $VPS_USERNAME@$VPS_IP:~/flask-app/
        ssh -i deploy_key -o StrictHostKeyChecking=no $VPS_USERNAME@$VPS_IP 'sh ~/deploy_script.sh'
